name: dbc
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - jupyterlab
  - termcolor
  - opencv
  - pillow
  - scikit-learn
  - scikit-image
  - scikit-video
  - tensorboard
  - tqdm
  - imageio
  - imageio-ffmpeg
  - pygame
  - networkx
  - dotmap
  - pip
  - dm_control
  - pip:
    - gym==0.25.2
    - labmaze==1.0.5
      # - dm_control
    - gym-dmc
      # - opencv-python
      # - pillow==6.1
      # - scikit-image
      # - scikit-video
      # - tb-nightly
      # - tqdm
      # - imageio
      # - imageio-ffmpeg
      # - pygame
      # - networkx
      # - dotmap
