name: dbc
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - jupyterlab
  - termcolor
  - opencv
  - pillow
  - scikit-learn
  - scikit-image
  - scikit-video
  - tensorboard
  - tqdm
  - imageio
  - imageio-ffmpeg
  - pygame
  - networkx
  - dotmap
  - pip
  - dm_control
  - pip:
    - gym==0.21
    - labmaze==1.0.5
    - gym-dmc
